/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import ss.englishteacher.DesktopController;

/**
 *
 * @author ssoch
 */
public class JWordFrame extends javax.swing.JFrame {

    private DesktopController controller;
    /**
     * Creates new form JWordFrame
     */
    public JWordFrame(DesktopController controller) {
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckAnswer_Button = new javax.swing.JButton();
        jNextWord_Button = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTranslatedWord_Label = new javax.swing.JLabel();
        jTranslation_TextField = new javax.swing.JTextField();
        jInfo_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jCheckAnswer_Button.setText("Check");
        jCheckAnswer_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckAnswer_ButtonMouseClicked(evt);
            }
        });

        jNextWord_Button.setText("Next");
        jNextWord_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNextWord_ButtonActionPerformed(evt);
            }
        });

        jButton3.setText("PL->EN");

        jTranslatedWord_Label.setText("translated word");

        jTranslation_TextField.setText("write translation");

        jInfo_Label.setText("Wynik ....");
        jInfo_Label.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckAnswer_Button)
                .addGap(18, 18, 18)
                .addComponent(jNextWord_Button)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTranslatedWord_Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTranslation_TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jInfo_Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTranslatedWord_Label, jTranslation_TextField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addGap(40, 40, 40)
                .addComponent(jTranslatedWord_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jTranslation_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jInfo_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckAnswer_Button)
                    .addComponent(jNextWord_Button))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTranslatedWord_Label, jTranslation_TextField});

        jCheckAnswer_Button.getAccessibleContext().setAccessibleName("jCheckAnswer_Button");
        jNextWord_Button.getAccessibleContext().setAccessibleName("jNextWord_Button");
        jButton3.getAccessibleContext().setAccessibleName("jLanguageMode");
        jTranslatedWord_Label.getAccessibleContext().setAccessibleName("jTranslatedWord_Label");
        jTranslation_TextField.getAccessibleContext().setAccessibleName("jTranslation_TextField");
        jInfo_Label.getAccessibleContext().setAccessibleName("jInfo_Label");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckAnswer_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckAnswer_ButtonMouseClicked
        controller.onCheck();
    }//GEN-LAST:event_jCheckAnswer_ButtonMouseClicked

    private void jNextWord_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNextWord_ButtonActionPerformed
        controller.onNext();
    }//GEN-LAST:event_jNextWord_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JWordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JWordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JWordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JWordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JWordFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jCheckAnswer_Button;
    public javax.swing.JLabel jInfo_Label;
    private javax.swing.JButton jNextWord_Button;
    public javax.swing.JLabel jTranslatedWord_Label;
    public javax.swing.JTextField jTranslation_TextField;
    // End of variables declaration//GEN-END:variables
}
